---
_extends: .github

repository:
  name: py-toxcore-c
  description: Python binding for Project-Tox the skype replacement.
  topics: toxcore, python, ffi

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - "bazel-opt"
          - "code-review/reviewable"
