---
language: python
sudo: false

addons:
  apt:
    packages:
      - libopus-dev
      - libvpx-dev

cache:
  directories:
    - $HOME/cache

jobs:
  include:
    - python: "2.6"
      before_script: &install_deps
        - export CACHE_DIR="$HOME/cache"
        - export CFLAGS="-I$CACHE_DIR/usr/include -fprofile-arcs -ftest-coverage"
        - export LDFLAGS="-L$CACHE_DIR/usr/lib"
        - export LD_LIBRARY_PATH="$CACHE_DIR/usr/lib"
        - export PKG_CONFIG_PATH="$CACHE_DIR/usr/lib/pkgconfig"
        - tools/install-deps.sh > /dev/null
      if: type IN (push, api, cron)
    - python: "2.7"
      before_script: *install_deps
    - python: "3.2"
      before_script: *install_deps
      if: type IN (push, api, cron)
    - python: "3.3"
      before_script: *install_deps
      if: type IN (push, api, cron)
    - python: "3.4"
      before_script: *install_deps
      if: type IN (push, api, cron)
    - python: "3.5"
      before_script: *install_deps
      if: type IN (push, api, cron)
    - python: "3.6"
      before_script: *install_deps
      install: pip install ndg-httpsclient urllib3[secure] cpp-coveralls
      after_script: coveralls
    - python: "nightly"
      before_script: *install_deps
      if: type IN (push, api, cron)
    - python: "3.6"
      install:
        - git clone --depth=1 https://github.com/TokTok/c-toxcore
        - mkdir -p _install/tox
        - cp c-toxcore/toxav/toxav.h c-toxcore/toxcore/tox.h c-toxcore/toxencryptsave/toxencryptsave.h _install/tox/
      script:
        - clang -fsyntax-only pytox/*.c -I/opt/python/3.6.3/include/python3.6m -I_install -Werror -Weverything -Wno-reserved-id-macro -Wno-documentation-deprecated-sync -Wno-shorten-64-to-32 -Wno-unused-parameter -Wno-missing-field-initializers -Wno-sign-conversion -Wno-padded -Wno-conversion
        - clang --analyze pytox/*.c -I/opt/python/3.6.3/include/python3.6m -I_install
    - language: generic
      services: docker
      script: docker build -t pytox .
      if: type IN (push, api, cron)

script:
  - python setup.py build_ext --inplace
  - PYTHONPATH=. python tests/tests.py
