---
version: 2

workflows:
  version: 2
  circleci:
    jobs:
      - asan
      - bazel-opt

jobs:
  asan:
    working_directory: ~/work
    docker:
      - image: ubuntu

    steps:
      - checkout
      - run: apt-get update
      - run: DEBIAN_FRONTEND=noninteractive
          apt-get install -y --no-install-recommends
          ca-certificates
          gcc
          g++
          cmake
          git
          libopus-dev
          libsodium-dev
          libvpx-dev
          ninja-build
          pkg-config
          python3-dev
          python3-pip
          python3-venv
      - run: python3 -m venv /tmp/path/to/venv
      - run: |
          . /tmp/path/to/venv/bin/activate
          pip install cython setuptools
      - run: git clone --depth=1 --recursive https://github.com/TokTok/c-toxcore
      - run: cd c-toxcore;
          . .github/scripts/flags-gcc.sh;
          add_flag -fsanitize=address;
          cmake -H. -B_build -GNinja
          -DCMAKE_C_FLAGS="$C_FLAGS"
          -DCMAKE_CXX_FLAGS="$CXX_FLAGS"
          -DCMAKE_EXE_LINKER_FLAGS="$LD_FLAGS"
          -DCMAKE_SHARED_LINKER_FLAGS="$LD_FLAGS"
          -DCMAKE_INSTALL_PREFIX:PATH="$PWD/_install"
          -DENABLE_STATIC=OFF
          -DMUST_BUILD_TOXAV=ON
      - run: cd c-toxcore/_build && ninja install -j$(nproc)
      - run: |
          . /tmp/path/to/venv/bin/activate
          export CFLAGS="-I$PWD/c-toxcore/_install/include -fsanitize=address,undefined"
          export LDFLAGS="-L$PWD/c-toxcore/_install/lib -Wl,-rpath,$PWD/c-toxcore/_install/lib"
          cython -I. $(find pytox -name "*.pyx")
          python3 setup.py build_ext --inplace
      - run: |
          . /tmp/path/to/venv/bin/activate
          export ASAN_OPTIONS=detect_leaks=0
          export LD_PRELOAD=libasan.so.8
          export PYTHONPATH=.
          python3 -m unittest $(find test -name "*_test.py")


  bazel-opt:
    working_directory: /tmp/cirrus-ci-build
    docker:
      - image: toxchat/toktok-stack:latest-release

    steps:
      - checkout
      - run: /src/workspace/tools/inject-repo py_toxcore_c
      - run: cd /src/workspace && bazel test -k //py_toxcore_c/...
