py_binary(
    name = "echo",
    srcs = ["echo.py"],
    data = ["//py_toxcore_c:pytox.so"],
    imports = [".."],
)

py_binary(
    name = "phone",
    srcs = ["phone.py"],
    data = ["//py_toxcore_c:pytox.so"],
    imports = [".."],
)
