name: ci

on:
  pull_request:
    branches: [master]

jobs:
  build:
    name: python-${{ matrix.version }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - version: "2.7"
          - version: "3.5"
          - version: "3.6"
          - version: "3.7"
          - version: "3.8"
          - version: "3.9"
          # TODO(robinlinden): Fix PY_SSIZE_T_CLEAN errors.
          # - version: "3.10"

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.version }}
    - name: Install
      run: |
          sudo apt update
          sudo apt install -y --no-install-recommends --no-install-suggests libtoxcore-dev
    - name: Build
      run: python setup.py build_ext --inplace
    - name: Test
      run: PYTHONPATH=. python tests/tests.py
